# Generated by Django 5.2.3 on 2025-06-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmetadata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='postmetadata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
