# Generated by Django 5.2.3 on 2025-06-21 10:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_postmetadata_created_at_postmetadata_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='postmetadata',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of tags for the post', size=None),
        ),
    ]
