# Generated by Django 5.2.3 on 2025-07-23 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_postlike_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostMediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='posts.postmetadata')),
            ],
        ),
    ]
