# Generated by Django 5.2.3 on 2025-10-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_postmediacontent'),
    ]

    operations = [
        migrations.AddField(
            model_name='postevent',
            name='str_address',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
