# Generated by Django 5.2.3 on 2025-10-02 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_postevent_str_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='postevent',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 10, 2, 17, 12, 45, 815090, tzinfo=datetime.timezone.utc)),
        ),
    ]
