# Generated by Django 5.2.3 on 2025-10-02 17:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_postevent_event_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postevent',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
