# Generated by Django 5.2.3 on 2025-07-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.TextField(default='https://i.imgur.com/QMJ67hC.png'),
        ),
    ]
