# Generated by Django 5.2.3 on 2025-07-30 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0002_alter_onboarding_channel'),
        ('pros', '0006_alter_sociallink_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('onboarded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pros.proplayer')),
            ],
        ),
    ]
