# Generated by Django 5.2.3 on 2025-07-31 14:13

import django.db.models.deletion
import entrance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0003_preregistration'),
        ('pros', '0006_alter_sociallink_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('code', models.CharField(default=entrance.models.get_six_digit_code, max_length=6)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='preregistration',
            name='onboarded_by',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pros.proplayer'),
        ),
    ]
