# Generated by Django 5.2.3 on 2025-08-02 12:49

import entrance.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0004_emailverification_alter_preregistration_onboarded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='is_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='preregistration',
            name='key',
            field=models.CharField(default=entrance.models.get_key, max_length=100),
        ),
    ]
