# Generated by Django 5.2.3 on 2025-08-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0005_preregistration_is_activated_preregistration_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preregistration',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
