# Generated by Django 5.2.3 on 2025-09-18 04:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0006_alter_preregistration_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='preregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
