# Generated by Django 5.2.3 on 2025-10-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0007_preregistration_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestAdress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.CharField(max_length=40)),
                ('long', models.CharField(max_length=40)),
                ('str_address', models.CharField(max_length=500)),
            ],
        ),
    ]
