# Generated by Django 5.2.3 on 2025-11-14 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0008_testadress'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestPayloadAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
            ],
        ),
    ]
