# Generated by Django 5.2.3 on 2025-11-14 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrance', '0009_testpayloadapi'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestPayloadAPI',
            new_name='TestPayload',
        ),
    ]
