# Generated by Django 5.2.3 on 2025-07-24 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_coverphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='introvideo',
            name='url',
            field=models.URLField(default='https://profiles.bowlersnetwork.com/default_intro_video.mp4', max_length=500),
        ),
    ]
