# Generated by Django 5.2.3 on 2025-08-01 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_introvideo_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityAndCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'City and Countries',
                'constraints': [models.UniqueConstraint(fields=('city', 'country'), name='unique_country_city_pair')],
            },
        ),
    ]
