# Generated by Django 5.2.3 on 2025-08-01 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_cityandcountry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityandcountry',
            name='city',
            field=models.CharField(max_length=500),
        ),
    ]
