# Generated by Django 5.2.3 on 2025-08-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_alter_cityandcountry_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='verification_code',
            field=models.CharField(default='', max_length=6),
        ),
    ]
