# Generated by Django 5.2.3 on 2025-08-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_alter_authcode_verification_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authcode',
            name='otp',
            field=models.CharField(default='', max_length=6),
        ),
    ]
