# Generated by Django 5.2.3 on 2025-11-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_userinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='city',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.DeleteModel(
            name='CityAndCountry',
        ),
        migrations.RemoveField(
            model_name='coverphoto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pic',
            name='user',
        ),
        migrations.RemoveField(
            model_name='address',
            name='details',
        ),
        migrations.RemoveField(
            model_name='address',
            name='post_code',
        ),
        migrations.AddField(
            model_name='address',
            name='address_str',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='address',
            name='lat',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='long',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='address',
            name='zip_code',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='birthdate',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='nickname',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='introvideo',
            name='url',
            field=models.URLField(default=None, max_length=500, null=True),
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='CoverPhoto',
        ),
        migrations.DeleteModel(
            name='Pic',
        ),
    ]
