# Generated by Django 5.2.3 on 2025-11-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_remove_city_country_remove_address_city_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
