# Generated by Django 5.2.2 on 2025-06-07 11:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_xpmap'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='xpmap',
            name='trigger',
        ),
        migrations.AddField(
            model_name='xpmap',
            name='trigger_codename',
            field=models.CharField(default='', help_text='e.g. onboarding', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='xpmap',
            name='trigger_detail',
            field=models.CharField(default='', help_text='e.g.on boarding a user', max_length=200),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='experience',
            field=models.IntegerField(default=0, help_text='Years (at least 0)', validators=[django.core.validators.MaxValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='xpmap',
            name='xp_worth',
            field=models.IntegerField(default=1, help_text='Must be greater than zero!', validators=[django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.CreateModel(
            name='XPLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gained_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xplogs', to=settings.AUTH_USER_MODEL)),
                ('xp_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='player.xpmap')),
            ],
        ),
    ]
