# Generated by Django 5.2.2 on 2025-06-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0005_alter_statistics_user_alter_user_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelxpmapping',
            name='card_theme_color',
            field=models.CharField(default='#8db85a', help_text='put in color name in lowercase e.g. blue.             Also takes hex e.g #8db85a or rgb e.g rgb(120, 200, 50)', max_length=20),
        ),
    ]
