# Generated by Django 5.2.2 on 2025-06-07 17:49

import player.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0006_levelxpmapping_card_theme_color'),
    ]

    operations = [
    
    ]
