# Generated by Django 5.2.2 on 2025-06-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0007_alter_user_profile_picture_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.TextField(default='https://api.dicebear.com/7.x/shapes/jpg?seed=default-avatar'),
        ),
    ]
