# Generated by Django 5.2.2 on 2025-06-07 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0008_alter_user_profile_picture_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='levelxpmapping',
            old_name='Level',
            new_name='level',
        ),
    ]
