# Generated by Django 5.2.2 on 2025-06-07 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0009_rename_level_levelxpmapping_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpmap',
            name='xp_worth',
            field=models.IntegerField(default=1, help_text='Must be greater than zero!', validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
