# Generated by Django 5.2.2 on 2025-06-08 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0010_alter_xpmap_xp_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='xplog',
            name='gained_xp',
            field=models.IntegerField(default=0),
        ),
    ]
