# Generated by Django 5.2.3 on 2025-06-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0011_xplog_gained_xp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='following',
        ),
    ]
