# Generated by Django 5.2.3 on 2025-06-21 07:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0012_remove_user_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistics',
            name='experience',
            field=models.IntegerField(default=0, help_text='Years (at least 0)', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
