# Generated by Django 5.2.3 on 2025-07-06 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0013_alter_statistics_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teaminvitation',
            name='team',
        ),
        migrations.RemoveField(
            model_name='teaminvitation',
            name='invited_user',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='TeamInvitation',
        ),
    ]
