# Generated by Django 5.2.3 on 2025-07-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0014_remove_teaminvitation_team_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cover_photo_url',
            field=models.URLField(default='https://profiles.bowlersnetwork.com/default-cover.png', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(default='https://profiles.bowlersnetwork.com/default-profile-pic.png', max_length=500),
        ),
    ]
