# Generated by Django 5.2.3 on 2025-11-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0015_user_cover_photo_url_alter_user_profile_picture_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistics',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
