# Generated by Django 5.2.3 on 2025-11-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0016_statistics_is_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cover_photo_url',
            field=models.URLField(default='https://profiles.bowlersnetwork.com/default_cp_refined.jpg', max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture_url',
            field=models.URLField(default='https://profiles.bowlersnetwork.com/default_pp_refined.jpg', max_length=500),
        ),
    ]
