# Generated by Django 5.2.3 on 2025-09-09 21:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tournamant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_date', models.DateTimeField()),
                ('reg_deadline', models.DateTimeField()),
                ('reg_fee', models.FloatField()),
                ('participants_count', models.IntegerField(default=1)),
                ('lat', models.CharField(default='', max_length=50)),
                ('long', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=300)),
                ('access_type', models.CharField(choices=[('Invitational', 'Invitational'), ('Open', 'Open')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('participant_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='tournaments.participantset')),
            ],
        ),
        migrations.AddField(
            model_name='participantset',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='tournaments.tournamant'),
        ),
        migrations.AddConstraint(
            model_name='participantset',
            constraint=models.UniqueConstraint(fields=('tournament', 'name'), name='unique_name_in_tournament'),
        ),
    ]
