# Generated by Django 5.2.3 on 2025-09-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournamant',
            name='name',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
    ]
