# Generated by Django 5.2.3 on 2025-09-09 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_alter_tournamant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantset',
            name='profile_picture',
            field=models.URLField(default=''),
        ),
    ]
