# Generated by Django 5.2.3 on 2025-09-18 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_participantset_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandicapTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.IntegerField(default=90)),
                ('average', models.IntegerField(default=200)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handicap', to='tournaments.tournamant')),
            ],
        ),
        migrations.CreateModel(
            name='ScratchTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average', models.IntegerField(default=200)),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scratch', to='tournaments.tournamant')),
            ],
        ),
    ]
