# Generated by Django 5.2.3 on 2025-09-29 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_handicaptournament_scratchtournament'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamant',
            name='average',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='tournamant',
            name='percentage',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='tournamant',
            name='tournament_type',
            field=models.CharField(choices=[('Handicap', 'Handicap'), ('Scratch', 'Scratch')], default='Scratch', max_length=30),
        ),
    ]
