# Generated by Django 5.2.3 on 2025-10-09 10:05

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournamant_average_tournamant_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamant',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='List of categories for the tournaments', size=None),
        ),
    ]
