# Generated by Django 5.2.3 on 2025-10-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_tournamant_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamant',
            name='event_banner',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='tournamant',
            name='logo',
            field=models.URLField(default=''),
        ),
    ]
