# Generated by Django 5.2.3 on 2025-10-29 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0002_center_alter_centeradmin_user_centeradmin_center'),
        ('tournaments', '0007_tournamant_event_banner_tournamant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamant',
            name='host',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='centers.center'),
        ),
    ]
