# Generated by Django 5.2.3 on 2025-10-30 00:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournamant_host'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournamant',
            name='address',
        ),
        migrations.RemoveField(
            model_name='tournamant',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='tournamant',
            name='long',
        ),
        migrations.AlterField(
            model_name='tournamant',
            name='categories',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text="Categories: Men's, Women's, Seniors', Juniors', Mixed", size=None),
        ),
    ]
