# Generated by Django 5.2.3 on 2025-11-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_remove_tournamant_address_remove_tournamant_lat_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentV0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('flyer', models.URLField(blank=True, default=None, null=True)),
            ],
        ),
    ]
