# Generated by Django 5.2.3 on 2025-11-14 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_tournamentv0'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentv0',
            name='director_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='tournamentv0',
            name='director_user_id',
            field=models.IntegerField(default=-1),
        ),
    ]
