# Generated by Django 5.2.3 on 2025-11-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_tournamentv0_director_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentv0',
            name='logo',
            field=models.URLField(blank=True, default=None, null=True),
        ),
    ]
