# Generated by Django 5.2.3 on 2025-11-18 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournamentv0_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentv0',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
    ]
