# Generated by Django 5.2.3 on 2025-07-11 05:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50, unique=True)),
                ('room_type', models.CharField(choices=[('Private', 'Private'), ('Group', 'Group')], default='Private', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='MessageMetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mymessages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.room')),
            ],
            options={
                'ordering': ['sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageMediaContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.messagemetadata')),
            ],
        ),
        migrations.CreateModel(
            name='MessageTextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.messagemetadata')),
            ],
        ),
        migrations.CreateModel(
            name='RoomMate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mates', to='chat.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['room', 'user'], name='chat_roomma_room_id_e28a3f_idx'), models.Index(fields=['user'], name='chat_roomma_user_id_968800_idx')],
                'constraints': [models.UniqueConstraint(fields=('room', 'user'), name='unique_room_mates')],
            },
        ),
    ]
