# Generated by Django 5.2.3 on 2025-07-13 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagemediacontent',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediacontents', to='chat.messagemetadata'),
        ),
        migrations.AlterField(
            model_name='messagetextcontent',
            name='metadata',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='textcontent', to='chat.messagemetadata'),
        ),
    ]
