# Generated by Django 5.2.3 on 2025-07-13 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('formal_name', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField()),
            ],
        ),
    ]
