# Generated by Django 5.2.3 on 2025-07-13 21:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('formal_name', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField()),
                ('brand_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sponsors.brandtype')),
            ],
        ),
    ]
