# Generated by Django 5.2.3 on 2025-11-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habijabi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaire',
            name='serial',
            field=models.IntegerField(default=-1),
        ),
    ]
