# Generated by Django 5.2.3 on 2025-11-12 10:59

import django.db.models.deletion
import habijabi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habijabi', '0002_questionnaire_serial'),
        ('pros', '0008_alter_proplayer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProsOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_onboard', models.BooleanField(default=False)),
                ('private_key', models.CharField(default=habijabi.models.get_key, max_length=100, unique=True)),
                ('is_notified', models.BooleanField(default=False)),
                ('has_answered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionnaireAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField()),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pros.proplayer')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habijabi.questionnaire')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pro', 'questionnaire'), name='unique_pro_questionnaire_pair')],
            },
        ),
    ]
