# Generated by Django 5.2.3 on 2025-11-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habijabi', '0003_prosonboarding_questionnaireanswers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionnaireanswers',
            name='answer',
            field=models.TextField(default=''),
        ),
    ]
