# Generated by Django 5.2.3 on 2025-11-19 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habijabi', '0004_alter_questionnaireanswers_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireanswers',
            name='email',
            field=models.EmailField(default=None, max_length=50, null=True),
        ),
    ]
