# Generated by Django 5.2.3 on 2025-11-19 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habijabi', '0005_questionnaireanswers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='QADraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=50)),
                ('a', models.TextField()),
                ('q', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='habijabi.questionnaire')),
            ],
        ),
    ]
