# Generated by Django 5.2.3 on 2025-07-13 23:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
        ('pros', '0002_alter_proplayer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsoredplayers', to='brands.brand')),
                ('pro_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='pros.proplayer')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pro_player', 'brand'), name='unique_sponsor_player_pair')],
            },
        ),
    ]
