# Generated by Django 5.2.3 on 2025-07-13 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0002_alter_proplayer_user'),
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProPlayerSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsors', to='pros.proplayer')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proplayers', to='sponsors.businesssponsor')),
            ],
        ),
    ]
