# Generated by Django 5.2.3 on 2025-07-13 22:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0003_proplayersponsor'),
        # ('sponsors', '0002_brandtype_brand'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proplayersponsor',
            options={'verbose_name_plural': 'Business sponsors'},
        ),
        migrations.CreateModel(
            name='ProPlayerBrandSponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proplayers', to='sponsors.brand')),
                ('pro_player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brandsponsors', to='pros.proplayer')),
            ],
            options={
                'verbose_name_plural': 'Brand sponsors',
            },
        ),
    ]
