# Generated by Django 5.2.3 on 2025-07-13 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0003_sponsors'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsors',
            options={'verbose_name_plural': 'Sponsors'},
        ),
    ]
