# Generated by Django 5.2.3 on 2025-07-24 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0004_alter_sponsors_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('logo', models.URLField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pros.proplayer')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pros.social')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('pro', 'social', 'url'), name='unique_social')],
            },
        ),
    ]
