# Generated by Django 5.2.3 on 2025-07-24 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0005_social_sociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='pro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='socials', to='pros.proplayer'),
        ),
    ]
