# Generated by Django 5.2.3 on 2025-08-02 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0006_alter_sociallink_pro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProPlayerRotator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pros.proplayer')),
            ],
        ),
    ]
