# Generated by Django 5.2.3 on 2025-11-15 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0008_alter_proplayer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='proplayer',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
