# Generated by Django 5.2.3 on 2025-11-21 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0009_proplayer_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proplayerrotator',
            name='last_pro',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pros.proplayer'),
        ),
    ]
