# Generated by Django 5.2.3 on 2025-11-23 03:17

import django.db.models.deletion
import tube.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(default=tube.models.generate_uid, max_length=150, unique=True)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(default='')),
                ('url', models.CharField(max_length=200, unique=True)),
                ('thumbnail_url', models.CharField(max_length=200, unique=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_public', models.BooleanField(default=True)),
                ('duration', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='large_videos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
