# Generated by Django 5.2.3 on 2025-11-24 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='largevideo',
            name='thumbnail_url',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
