# Generated by Django 5.2.3 on 2025-11-30 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0002_alter_largevideo_thumbnail_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='largevideo',
            name='thumbnail_url',
            field=models.CharField(default='https://cdn.bowlersnetwork.com/thumbnail.png', max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='LargeVideoComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('large_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tube.largevideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LargeVideoLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('large_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='tube.largevideo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
