# Generated by Django 5.2.3 on 2025-11-30 13:17

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tube', '0003_alter_largevideo_thumbnail_url_largevideocomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='largevideocomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
