# Generated by Django 5.2.3 on 2025-07-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='default', max_length=20, unique=True)),
                ('backend', models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=100)),
                ('host', models.CharField(default='smtp.hostinger.com', max_length=100)),
                ('port', models.IntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailCred',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Email Credentials',
            },
        ),
    ]
