# Generated by Django 5.2.3 on 2025-07-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfig',
            name='backend',
            field=models.CharField(default='django.core.mail.backends.smtp.EmailBackend', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='host',
            field=models.CharField(default='smtp.hostinger.com', editable=False, max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='name',
            field=models.CharField(default='default', editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='port',
            field=models.IntegerField(default=587, editable=False),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='use_tls',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AlterField(
            model_name='emailcred',
            name='email',
            field=models.EmailField(editable=False, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='emailcred',
            name='password',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
