# Generated by Django 5.2.3 on 2025-07-28 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsystem', '0002_alter_emailconfig_backend_alter_emailconfig_host_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcred',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='emailcred',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
