# Generated by Django 5.2.3 on 2025-07-29 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailsystem', '0003_alter_emailcred_email_alter_emailcred_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcred',
            name='key',
            field=models.CharField(default='system', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='backend',
            field=models.CharField(default='django.core.mail.backends.smtp.EmailBackend', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='host',
            field=models.CharField(default='smtp.hostinger.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='name',
            field=models.CharField(default='default', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='port',
            field=models.IntegerField(default=587),
        ),
        migrations.AlterField(
            model_name='emailconfig',
            name='use_tls',
            field=models.BooleanField(default=True),
        ),
    ]
