# Generated by Django 5.2.3 on 2025-11-11 07:33

import onboarding.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProsOnboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_onboard', models.BooleanField(default=False)),
                ('private_key', models.CharField(default=onboarding.models.get_key, max_length=100, unique=True)),
            ],
        ),
    ]
