# Generated by Django 5.2.3 on 2025-11-11 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0001_initial'),
        ('pros', '0007_proplayerrotator'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionnaireAnswers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('description', models.TextField()),
                ('answer', models.TextField()),
                ('pro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pros.proplayer')),
            ],
        ),
    ]
