# Generated by Django 5.2.3 on 2025-11-11 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0002_questionnaireanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionnaireanswers',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
