# Generated by Django 5.2.3 on 2025-11-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0003_questionnaireanswers_is_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireanswers',
            name='is_notified',
        ),
        migrations.AddField(
            model_name='prosonboarding',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
