# Generated by Django 5.2.3 on 2025-11-11 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0004_remove_questionnaireanswers_is_notified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='prosonboarding',
            name='has_answered',
            field=models.BooleanField(default=False),
        ),
    ]
