# Generated by Django 5.2.3 on 2025-11-12 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0005_prosonboarding_has_answered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionnaireanswers',
            name='description',
        ),
        migrations.RemoveField(
            model_name='questionnaireanswers',
            name='question',
        ),
        migrations.AddField(
            model_name='questionnaireanswers',
            name='ques_id',
            field=models.IntegerField(default=-1),
        ),
    ]
