# Generated by Django 5.2.3 on 2025-11-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onboarding', '0006_remove_questionnaireanswers_description_and_more'),
        ('pros', '0007_proplayerrotator'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='questionnaireanswers',
            constraint=models.UniqueConstraint(fields=('pro', 'ques_id'), name='unique_pro_ques_id_pair'),
        ),
    ]
