# Generated by Django 5.2.3 on 2025-10-29 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('centers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Center',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('address_str', models.CharField(max_length=200, unique=True)),
                ('lat', models.CharField(max_length=30)),
                ('long', models.CharField(max_length=30)),
                ('logo', models.URLField(default='https://logos.bowlersnetwork.com/pinsX.jpg', max_length=500)),
            ],
        ),
        migrations.AlterField(
            model_name='centeradmin',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='centermanager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='centeradmin',
            name='center',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin', to='centers.center'),
        ),
    ]
